src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $lastName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $born_at;

    /**
     * @ORM\ManyToOne(targetEntity=Level::class, inversedBy="students")
     * @ORM\JoinColumn(nullable=false)
     */
    private $level;

    /**
     * @ORM\OneToMany(targetEntity=Lease::class, mappedBy="student")
     */
    private $leases;

    public function __construct()
    {
        $this->leases = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBornAt(): ?\DateTimeInterface
    {
        return $this->born_at;
    }

    public function setBornAt(\DateTimeInterface $born_at): self
    {
        $this->born_at = $born_at;

        return $this;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): self
    {
        $this->level = $level;

        return $this;
    }

    /**
     * @return Collection|Lease[]
     */
    public function getLeases(): Collection
    {
        return $this->leases;
    }

    public function addLease(Lease $lease): self
    {
        if (!$this->leases->contains($lease)) {
            $this->leases[] = $lease;
            $lease->setStudent($this);
        }

        return $this;
    }

    public function removeLease(Lease $lease): self
    {
        if ($this->leases->contains($lease)) {
            $this->leases->removeElement($lease);
            // set the owning side to null (unless already changed)
            if ($lease->getStudent() === $this) {
                $lease->setStudent(null);
            }
        }

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use App\Entity\Level;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName',null,[
                'label'=> 'Prénoms :'
            ])
            ->add('lastName',null,[
                'label' => 'Nom:'
            ])
            ->add('born_at', null, [
                'label' => 'Date de Naissance'
            ])
            ->add('level', EntityType::class,[
                'class' => Level::class,
                'choice_label' => 'name'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/student")
 */
class StudentController extends AbstractController
{
    /**
     * @Route("/", name="student_index", methods={"GET"})
     */
    public function index(StudentRepository $studentRepository): Response
    {
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="student_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($student);
            $entityManager->flush();
            $this->addFlash('success', "L'élève a été bien ajouté");

            return $this->redirectToRoute('student_index');
        }

        return $this->render('student/new.html.twig', [
            'student' => $student,
            'formStudent' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_show", methods={"GET"})
     */
    public function show(Student $student): Response
    {
        return $this->render('student/show.html.twig', [
            'student' => $student,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="student_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Student $student): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', "L'élève a été bien modifié");

            return $this->redirectToRoute('student_index');
        }

        return $this->render('student/edit.html.twig', [
            'student' => $student,
            'formStudent' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="student_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Student $student): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($student);
            $entityManager->flush();
            $this->addFlash('success', "L'élève a été bien supprimé");
        }

        return $this->redirectToRoute('student_index');
    }
}

templates/student/_delete_form.html.twig
<form method="post" action="{{ path('student_delete', {'id': student.id}) }}" onsubmit="return confirm('Etes vous vraiment sur de supprimer cet éleve?');" style="display: inline-block;">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn btn-danger">supprimer</button>
</form>

templates/student/_form.html.twig
<div class="container">
    {{ form_start(formStudent) }}
    <div class="row">
        <div class="col-md-4">{{ form_row(formStudent.firstName,{'attr': { 'placeholder' : "votre prenom ...."}}) }}</div>
        <div class="col-md-4"> {{ form_row(formStudent.lastName,{'attr': { 'placeholder' : "votre nom ...."}}) }}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{ form_row(formStudent.level) }}</div>
        <div class="col-md-5">{{ form_row(formStudent.born_at) }}</div>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    <a href="{{ path('student_index') }}" class="btn btn-primary">retour a la liste des éleves</a>
    {{ form_end(formStudent) }}
</div>

templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer Eleve{% endblock %}

{% block body %}
    <h3>Modifier les informations de l'eleve</h3>

    {{ include('student/_form.html.twig', {'button_label': 'Modifier'}) }}


{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des élèves{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <h1 class="text-center">Liste des  élèves</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prénoms</th>
                <th>Noms</th>
                <th>Date de Naissance</th>
                <th>Level</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.firstName }}</td>
                <td>{{ student.lastName }}</td>
                <td>{{ student.bornAt ? student.bornAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.level.name }}</td>
                <td>
                    <a href="{{ path('student_edit', {'id': student.id}) }}" class="btn btn-secondary">Editer</a>
                    {{ include('student/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Pas d'etudiants trouvés</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="text-right">
    <a href="{{ path('student_new') }}"class="btn btn-primary">Ajouter un Eleve</a>
</div>
{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout Eleve{% endblock %}

{% block body %}
    <h2>Ajout d'un Eleve</h2>

    {{ include('student/_form.html.twig') }}

{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student{% endblock %}

{% block body %}
    <h1>Student</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ student.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ student.lastName }}</td>
            </tr>
            <tr>
                <th>Born_at</th>
                <td>{{ student.bornAt ? student.bornAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('student_index') }}">back to list</a>

    <a href="{{ path('student_edit', {'id': student.id}) }}">edit</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}