src/Entity/Lease.php
<?php

namespace App\Entity;

use App\Repository\LeaseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LeaseRepository::class)
 */
class Lease
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $begin;

    /**
     * @ORM\Column(type="date")
     */
    private $end;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Student::class, inversedBy="leases")
     * @ORM\JoinColumn(nullable=false)
     */
    private $student;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="leases")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Examplar::class, inversedBy="leases")
     * @ORM\JoinColumn(nullable=false)
     */
    private $examplar;

    /**
     * @ORM\OneToOne(targetEntity=Penality::class, mappedBy="lease", cascade={"persist", "remove"})
     */
    private $penality;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->end = null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBegin(): ?\DateTimeInterface
    {
        return $this->begin;
    }

    public function setBegin(\DateTimeInterface $begin): self
    {
        $this->begin = $begin;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getExamplar(): ?Examplar
    {
        return $this->examplar;
    }

    public function setExamplar(?Examplar $examplar): self
    {
        $this->examplar = $examplar;

        return $this;
    }

    public function getPenality(): ?Penality
    {
        return $this->penality;
    }

    public function setPenality(Penality $penality): self
    {
        $this->penality = $penality;

        // set the owning side of the relation if necessary
        if ($penality->getLease() !== $this) {
            $penality->setLease($this);
        }

        return $this;
    }
}

src/Form/LeaseType.php
<?php

namespace App\Form;

use App\Entity\Examplar;
use App\Entity\Lease;
use App\Entity\Student;
use phpDocumentor\Reflection\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LeaseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('begin')
            ->add('student', EntityType::class, [
                'class' => Student::class,
                'choice_label' => function (Student $student) {
                    return $student->getFirstName() . ' ' . $student->getLastName();
                },
            ])
            ->add('examplar', EntityType::class, [
                'class' => Examplar::class,
                'choice_label' => function (Examplar $examplar) {
                    return $examplar->getBook()->getTitle() . ' Isbn: ' . $examplar->getIsbn();
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lease::class,
        ]);
    }
}

src/Controller/LeaseController.php
<?php

namespace App\Controller;

use App\Entity\Lease;
use App\Form\LeaseType;
use App\Form\LeaseEditType;
use App\Repository\LeaseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/lease")
 */
class LeaseController extends AbstractController
{
    /**
     * @Route("/", name="lease_index", methods={"GET"})
     * @param LeaseRepository $leaseRepository
     * @return Response
     */
    public function index(LeaseRepository $leaseRepository): Response
    {
        return $this->render('lease/index.html.twig', [
            'leases' => $leaseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="lease_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lease = new Lease();
        $form = $this->createForm(LeaseType::class, $lease);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $lease->setUser($this->getUser());
            $leaseid = $form['student']->getData()->getId();
            $leaseCount = count($this->getDoctrine()->getRepository(Lease::class)->findBy(['end' => null, 'student' => $leaseid]));
            if ($leaseCount < 2 )
            {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($lease);
                $entityManager->flush();
                $this->addFlash('success', 'Location éffectuée');
            }
            else
            {
                $this->addFlash('error', 'Deux locations en cours');
                return $this->redirectToRoute('lease_new');
            }

            return $this->redirectToRoute('lease_index');
        }

        return $this->render('lease/new.html.twig', [
            'lease' => $lease,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="lease_show", methods={"GET"})
     */
    public function show(Lease $lease): Response
    {
        return $this->render('lease/show.html.twig', [
            'lease' => $lease,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="lease_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Lease $lease): Response
    {
        $form = $this->createForm(LeaseEditType::class, $lease);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $leaseend = $form['end']->getData();
            $leasebegin = $lease->getBegin();
            if ($leasebegin < $leaseend)
            {
                $this->getDoctrine()->getManager()->flush();
                $this->addFlash('success', 'Locations terminer');
                return $this->redirectToRoute('lease_index');
            }
            else
            {
                $this->addFlash('error', 'La date doit être supérieur à la date de location');
            }
        }

        return $this->render('lease/edit.html.twig', [
            'lease' => $lease,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lease_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Lease $lease): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lease->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($lease);
            $entityManager->flush();
        }

        return $this->redirectToRoute('lease_index');
    }
}

templates/lease/_delete_form.html.twig
<form method="post" action="{{ path('lease_delete', {'id': lease.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lease.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lease/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-4">{{ form_row(form.student) }}</div>
    <div class="col-md-4">{{ form_row(form.examplar) }}</div>
    <div class="col-md-4">{{ form_row(form.begin) }}</div>
</div>
    {{ form_rest(form) }}
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/lease/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lease{% endblock %}

{% block body %}
    <h1>Edit Lease</h1>
    <br>
    <alert class="alert alert-warning">
        Mettre fin la location de <strong>{{ lease.student.firstName }} {{ lease.student.lastName }}</strong> qui a débuté le <strong>{{ lease.begin ? lease.begin|date('Y-m-d') : '' }}</strong> ?
    </alert>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-4">{{ form_row(form.end) }}</div>
    </div>
    {{ form_rest(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('lease_index') }}">back to list</a>

    {{ include('lease/_delete_form.html.twig') }}
{% endblock %}

templates/lease/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lease index{% endblock %}

{% block body %}
    <h1>Liste des locations</h1>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <table class="table">
        <thead>
        <tr>
            <th>Utilisateur</th>
            <th>Eleve</th>
            <th>Livre</th>
            <th>Début</th>
            <th>Fin</th>
            <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lease in leases %}
            <tr>
                <td>{{ lease.user.name }}</td>
                <td>{{ lease.student.firstName }} {{ lease.student.lastName }}</td>
                <td>{{ lease.examplar.book.title }}</td>
                <td>{{ lease.begin ? lease.begin|date('Y-m-d') : '' }}</td>
                <td>{% if lease.end is not null %}{{ lease.end ? lease.end|date('Y-m-d') : '' }}{% else %} En cours{% endif %}</td>
                <td>
                    {% if lease.end is null %}<a href="{{ path('lease_edit', {'id': lease.id}) }}">Terminer</a>{% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('lease_new') }}">Nouvelle Location</a>
{% endblock %}

templates/lease/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lease{% endblock %}

{% block body %}
    <h1>Démarrer une location</h1>

    {{ include('lease/_form.html.twig') }}

    <a href="{{ path('lease_index') }}">Retour à la liste de location</a>
{% endblock %}

templates/lease/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lease{% endblock %}

{% block body %}
    <h1>Lease</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lease.id }}</td>
            </tr>
            <tr>
                <th>Begin</th>
                <td>{{ lease.begin ? lease.begin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ lease.end ? lease.end|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ lease.createdAt ? lease.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('lease_index') }}">back to list</a>

    <a href="{{ path('lease_edit', {'id': lease.id}) }}">edit</a>

    {{ include('lease/_delete_form.html.twig') }}
{% endblock %}